-- ============================================================================
-- V202607120313__init_schema_v1.sql
-- 한땀한땀 — 공예품 DIY 제작자 구독 플랫폼 : 초기 스키마
-- 기준 문서: slack - 기획 채널 - 03_ERD_설계.md (2026-07-12)
-- 대상: PostgreSQL 16 / 적용: Flyway
--
-- [작성 원칙]
--  * ENUM 값은 VARCHAR + CHECK로 관리한다 (Java에서는 @Enumerated(EnumType.STRING)).
--  * PK는 BIGINT GENERATED BY DEFAULT AS IDENTITY (JPA IDENTITY 전략과 호환).
--  * created_at/updated_at은 DB DEFAULT now() + 애플리케이션(JPA Auditing) 관리.
--      -> 해당 내용은 managed on `global - JpaAuditingConfig.java`
--  * 콘텐츠 테이블은 소프트 삭제 기본 (공통 설계 규칙).
--  * FK는 전부 ON DELETE 기본(NO ACTION) — 소프트 삭제 기반이므로 물리 연쇄 삭제를 열지 않음.
--  * ERD 문서의 "추가 제약조건" 표에 명시된 항목은 CHECK/UNIQUE로, 여러 행을 가로지르는
--    검증(부모 댓글의 feed_id 일치, 크리에이터 프로필 생성 시 role 검증)은 트리거로 구현했다.
--  * 정의서에 명시되지 않았지만 보완/추정한 지점은 [NOTE]로 표기 → 시나리오 테스트 때 재검증 대상. 어플리케이션 레이어 검증 희망 시, 고민 및 해결 방안 공유로 학습
-- ============================================================================
-- ============================================================
-- 1. 회원 (MEMBER)
-- ============================================================
CREATE TABLE member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255), -- OAuth 가입자는 NULL
    nickname VARCHAR(255) NOT NULL,
    profile_image_url VARCHAR(500),
    profile_image_storage_key VARCHAR(500),
    role VARCHAR(50) NOT NULL DEFAULT 'USER',
    oauth_provider VARCHAR(50) NOT NULL DEFAULT 'NONE',
    oauth_id VARCHAR(255),
    email_verified_at TIMESTAMPTZ, -- NULL = 미인증
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_member_email UNIQUE (email),
    CONSTRAINT uq_member_nickname UNIQUE (nickname),
    CONSTRAINT uq_member_oauth UNIQUE (oauth_provider, oauth_id),
    CONSTRAINT ck_member_role CHECK (role IN ('USER', 'CREATOR', 'ADMIN')),
    CONSTRAINT ck_member_oauth_provider CHECK (oauth_provider IN ('NONE', 'GOOGLE')),
    CONSTRAINT ck_member_auth_source CHECK (
        (
            oauth_provider = 'NONE'
            AND password IS NOT NULL
        )
        OR (
            oauth_provider <> 'NONE'
            AND oauth_id IS NOT NULL
        )
    )
);

COMMENT ON TABLE member IS '전체 사용자(비회원 제외) — 일반 회원, 크리에이터, 관리자';

-- ============================================================
-- 1-2. 이메일 인증 토큰 (EMAIL_VERIFICATION)  AUTH-004~007, NFR-002·003
-- ============================================================
CREATE TABLE email_verification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT, -- 가입 전 인증이면 NULL 가능
    email VARCHAR(255) NOT NULL,
    purpose VARCHAR(50) NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    used_at TIMESTAMPTZ, -- 사용 전 NULL, 1회 사용 후 값 채워짐
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_email_verification_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT uq_email_verification_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_email_verification_purpose CHECK (purpose IN ('SIGNUP', 'PASSWORD_RESET')),
    CONSTRAINT ck_email_verification_status CHECK (status IN ('PENDING', 'VERIFIED', 'EXPIRED'))
);

CREATE INDEX idx_email_verification_email_purpose ON email_verification (email, purpose, created_at DESC);

COMMENT ON TABLE email_verification IS '이메일 인증 토큰 — 회원/이메일 기준 1:N 이력';

-- ============================================================
-- 2. 크리에이터 (CREATOR)
-- ============================================================
CREATE TABLE creator_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    introduction TEXT,
    representative_image_url VARCHAR(500),
    representative_image_storage_key VARCHAR(500),
    cover_image_url VARCHAR(500),
    cover_image_storage_key VARCHAR(500),
    benefits_description TEXT,
    subscription_price INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_creator_profile_member UNIQUE (member_id),
    CONSTRAINT fk_creator_profile_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT ck_creator_profile_price CHECK (subscription_price >= 0)
);

COMMENT ON TABLE creator_profile IS '크리에이터 전용 정보 (MEMBER와 1:0..1).';

-- 추가 제약조건: "역할 검증 — MEMBER.role = CREATOR인 회원만 프로필 생성"
-- 어플리케이션 레이어에서 검증 고민 할 수 있도록 우선 트리거 로직을 주석 처리
/* 
CREATE OR REPLACE FUNCTION fn_creator_profile_check_role() RETURNS TRIGGER AS $$
BEGIN
IF NOT EXISTS (SELECT 1 FROM member WHERE id = NEW.member_id AND role = 'CREATOR') THEN
RAISE EXCEPTION 'creator_profile.member_id(%) is not a member with role=CREATOR', NEW.member_id;
END IF;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_creator_profile_check_role
BEFORE INSERT OR UPDATE OF member_id ON creator_profile
FOR EACH ROW EXECUTE FUNCTION fn_creator_profile_check_role();
*/
CREATE TABLE creator_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    reviewed_by BIGINT,
    reject_reason VARCHAR(500), -- [NOTE] 컬럼 표엔 없으나 "거절 처리" 정책이 저장을 명시 → 보완
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    reviewed_at TIMESTAMPTZ,
    CONSTRAINT fk_creator_application_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_creator_application_reviewer FOREIGN KEY (reviewed_by) REFERENCES member (id),
    CONSTRAINT ck_creator_application_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

-- 정책: "중복 대기 신청 — 동일 회원에게 PENDING 신청이 있으면 추가 신청 차단"
CREATE UNIQUE INDEX uq_creator_application_pending ON creator_application (member_id)
WHERE
    status = 'PENDING';

CREATE INDEX idx_creator_application_status ON creator_application (status, applied_at);

COMMENT ON TABLE creator_application IS '크리에이터 전환 신청 (CREATOR-001~004) — 신청 이력은 삭제하지 않고 유지';

-- ============================================================
-- 3. 카테고리 (CATEGORY)
-- ============================================================
CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_category_name UNIQUE (name)
);

COMMENT ON TABLE category IS '공예·DIY 카테고리 — 삭제 대신 is_active로 비활성화, FEED→PROJECT→CATEGORY 경로로 분류';

-- ============================================================
-- 4. 프로젝트 (PROJECT) — 크리에이터의 피드 폴더
-- ============================================================
CREATE TABLE project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    cover_image_url VARCHAR(500),
    cover_image_storage_key VARCHAR(500),
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_project_creator FOREIGN KEY (creator_id) REFERENCES member (id),
    CONSTRAINT fk_project_category FOREIGN KEY (category_id) REFERENCES category (id)
);

CREATE INDEX idx_project_creator ON project (creator_id)
WHERE
    is_deleted = false;

CREATE INDEX idx_project_category ON project (category_id);

COMMENT ON TABLE project IS '크리에이터의 피드 폴더. 피드 수는 COUNT(FEED.id)로 계산하며 컬럼으로 저장하지 않음(정책). 활성 피드 존재 시 삭제 차단, 카테고리 변경 시 소속 피드 전체가 새 카테고리로 조회됨 — 둘 다 앱 레이어 책임';

-- ============================================================
-- 5. 피드 (FEED)
-- ============================================================
CREATE TABLE feed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    visibility VARCHAR(50) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    comment_count BIGINT NOT NULL DEFAULT 0, -- 반정규화 카운터, 댓글/좋아요 등록·취소 시 트랜잭션으로 갱신 : 앱 레이어에서의 책임, 개발 방향성 지향
    like_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_feed_project FOREIGN KEY (project_id) REFERENCES project (id),
    CONSTRAINT ck_feed_visibility CHECK (
        visibility IN ('PUBLIC', 'FREE_SUBSCRIBER', 'PAID_SUBSCRIBER')
    )
);

CREATE INDEX idx_feed_project_created ON feed (project_id, created_at DESC)
WHERE
    is_deleted = false;

COMMENT ON TABLE feed IS 'SNS 피드 — 프로젝트에 종속되며 카테고리/크리에이터는 PROJECT를 통해서만 조회 (FEED에 직접 컬럼 없음, ERD 명시)';

CREATE TABLE feed_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    url VARCHAR(1000) NOT NULL,
    storage_key VARCHAR(500),
    original_name VARCHAR(255),
    file_size BIGINT,
    mime_type VARCHAR(100),
    order_index INT NOT NULL DEFAULT 0,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_feed_attachment_feed FOREIGN KEY (feed_id) REFERENCES feed (id),
    CONSTRAINT ck_feed_attachment_type CHECK (type IN ('IMAGE', 'VIDEO_LINK', 'FILE'))
);

CREATE INDEX idx_feed_attachment_feed ON feed_attachment (feed_id, order_index)
WHERE
    is_deleted = false;

COMMENT ON TABLE feed_attachment IS '피드 첨부 — 이미지 / 외부 영상 링크 / 다운로드 자료 통합 (MEDIA-001·003·004)';

-- ============================================================
-- 6. 피드 소셜 (댓글 / 좋아요)
-- ============================================================
CREATE TABLE feed_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    parent_comment_id BIGINT,
    depth SMALLINT NOT NULL DEFAULT 0,
    content VARCHAR(1000) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_feed_comment_feed FOREIGN KEY (feed_id) REFERENCES feed (id),
    CONSTRAINT fk_feed_comment_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_feed_comment_parent FOREIGN KEY (parent_comment_id) REFERENCES feed_comment (id),
    CONSTRAINT ck_feed_comment_depth CHECK (depth IN (0, 1)),
    CONSTRAINT ck_feed_comment_parent CHECK (
        (
            depth = 0
            AND parent_comment_id IS NULL
        )
        OR (
            depth = 1
            AND parent_comment_id IS NOT NULL
        )
    )
);

CREATE INDEX idx_feed_comment_feed ON feed_comment (feed_id, created_at);

CREATE INDEX idx_feed_comment_parent ON feed_comment (parent_comment_id);

-- 추가 제약조건: "부모 댓글 검증 — 부모 댓글과 자식 댓글의 feed_id가 같아야 함" (여러 행 참조 → 트리거)
-- 어플리케이션 레이어에서 검증 고민 할 수 있도록 우선 트리거 로직을 주석 처리
/*
CREATE OR REPLACE FUNCTION fn_feed_comment_check_parent() RETURNS TRIGGER AS $$
DECLARE
parent_feed_id BIGINT;
BEGIN
IF NEW.parent_comment_id IS NOT NULL THEN
SELECT feed_id INTO parent_feed_id FROM feed_comment WHERE id = NEW.parent_comment_id;
IF parent_feed_id IS DISTINCT FROM NEW.feed_id THEN
RAISE EXCEPTION 'feed_comment.parent_comment_id(%) belongs to a different feed', NEW.parent_comment_id;
END IF;
END IF;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_feed_comment_check_parent
BEFORE INSERT OR UPDATE OF parent_comment_id, feed_id ON feed_comment
FOR EACH ROW EXECUTE FUNCTION fn_feed_comment_check_parent();
*/
COMMENT ON TABLE feed_comment IS '피드 댓글·대댓글 — self-reference, 깊이 1단계 제한';

CREATE TABLE feed_like (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_feed_like_feed FOREIGN KEY (feed_id) REFERENCES feed (id),
    CONSTRAINT fk_feed_like_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT uq_feed_like UNIQUE (feed_id, member_id)
);

CREATE INDEX idx_feed_like_member ON feed_like (member_id);

COMMENT ON TABLE feed_like IS '피드 좋아요 (SOCIAL-005~006)';

-- ============================================================
-- 7. 피드 투표 (POLL)
-- ============================================================
CREATE TABLE poll (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_id BIGINT NOT NULL,
    question VARCHAR(500) NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    is_closed BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_poll_feed UNIQUE (feed_id),
    CONSTRAINT fk_poll_feed FOREIGN KEY (feed_id) REFERENCES feed (id)
);

COMMENT ON TABLE poll IS '피드 투표 — 피드당 0..1개';

CREATE TABLE poll_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id BIGINT NOT NULL,
    option_text VARCHAR(200) NOT NULL,
    order_index INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_poll_option_poll FOREIGN KEY (poll_id) REFERENCES poll (id),
    CONSTRAINT uq_poll_option_order UNIQUE (poll_id, order_index)
);

COMMENT ON TABLE poll_option IS '투표 선택지 (POLL-002)';

CREATE TABLE poll_vote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id BIGINT NOT NULL,
    poll_option_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    weight SMALLINT NOT NULL, -- 무료 1, 유료 2 (서버가 구독 상태 확인 후 결정)
    subscription_level_snapshot VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_poll_vote_poll FOREIGN KEY (poll_id) REFERENCES poll (id),
    CONSTRAINT fk_poll_vote_option FOREIGN KEY (poll_option_id) REFERENCES poll_option (id),
    CONSTRAINT fk_poll_vote_member FOREIGN KEY (member_id) REFERENCES member (id),
    -- 회원당 투표 1건(선택지 변경은 UPDATE) — ERD 문서 기준. 
    -- 01_요구사항정의(POLL-006, 유료 최대 2개 선택)와 상충 가능성 있음
    -- [ISSUE] 시나리오 테스트 전 확인 필요, 하단 "3. 시나리오 테스트에 앞선 분석" 참고
    -- Resolved Issue : 한 건의 선택에 가중치를 부여하는 방식 - 성민(07/12)
    CONSTRAINT uq_poll_vote UNIQUE (poll_id, member_id),
    CONSTRAINT ck_poll_vote_level CHECK (subscription_level_snapshot IN ('FREE', 'PAID')),
    CONSTRAINT ck_poll_vote_weight CHECK (weight IN (1, 2))
);

CREATE INDEX idx_poll_vote_option ON poll_vote (poll_option_id);

COMMENT ON TABLE poll_vote IS '회원별 투표 내역 (POLL-005~007) — 선택은 1개 고정, 차이는 weight(가중치)';

-- ============================================================
-- 8. 구독 (SUBSCRIPTION)
-- ============================================================
CREATE TABLE subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscriber_id BIGINT NOT NULL,
    creator_id BIGINT NOT NULL,
    subscription_level VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL, -- ACTIVE / CANCEL_SCHEDULED (비구독 = 행 없음)
    subscription_price_snapshot INT,
    auto_renew BOOLEAN NOT NULL DEFAULT false,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    current_period_start_at TIMESTAMPTZ,
    current_period_end_at TIMESTAMPTZ,
    cancel_scheduled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_subscription_subscriber FOREIGN KEY (subscriber_id) REFERENCES member (id),
    CONSTRAINT fk_subscription_creator FOREIGN KEY (creator_id) REFERENCES member (id),
    CONSTRAINT uq_subscription UNIQUE (subscriber_id, creator_id),
    CONSTRAINT ck_subscription_level CHECK (subscription_level IN ('FREE', 'PAID')),
    CONSTRAINT ck_subscription_status CHECK (status IN ('ACTIVE', 'CANCEL_SCHEDULED')),
    -- [NOTE] 정의서에 명시 없으나 자기 자신 구독 방지 보완
    CONSTRAINT ck_subscription_self CHECK (subscriber_id <> creator_id)
);

CREATE INDEX idx_subscription_creator ON subscription (creator_id, subscription_level, status);

CREATE INDEX idx_subscription_period_end ON subscription (current_period_end_at)
WHERE
    subscription_level = 'PAID';

COMMENT ON TABLE subscription IS '회원-크리에이터 구독 관계 — 등급(FREE/PAID)과 처리 상태 분리, 비구독은 행 없음';

-- ============================================================
-- 9. 결제 (PAYMENT)
-- ============================================================
CREATE TABLE payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    order_id VARCHAR(255) NOT NULL, -- 서비스 주문 ID
    pg_transaction_id VARCHAR(255), -- Toss paymentKey 등, 승인 전에는 NULL
    idempotency_key VARCHAR(255) NOT NULL, -- 클라이언트가 생성해 재시도 시에도 동일 값 유지
    amount INT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    payment_method VARCHAR(50),
    failure_code VARCHAR(100),
    failure_message VARCHAR(500),
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_payment_subscription FOREIGN KEY (subscription_id) REFERENCES subscription (id),
    CONSTRAINT fk_payment_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT uq_payment_order_id UNIQUE (order_id),
    CONSTRAINT uq_payment_pg_tx UNIQUE (pg_transaction_id),
    CONSTRAINT uq_payment_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_payment_status CHECK (
        status IN ('PENDING', 'SUCCESS', 'FAILED', 'CANCELED')
    ),
    CONSTRAINT ck_payment_amount CHECK (amount >= 0)
);

CREATE INDEX idx_payment_subscription ON payment (subscription_id, created_at DESC);

CREATE INDEX idx_payment_member ON payment (member_id, created_at DESC);

COMMENT ON TABLE payment IS '유료 구독 결제 내역 — 카드번호 미저장(NFR-009), order_id/pg_transaction_id/idempotency_key 3중 멱등 방어';

-- ============================================================
-- 10. 유료 게시판 (BOARD) — Q&A, 프로젝트와 무관한 별도 공간
-- ============================================================
CREATE TABLE board_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id BIGINT NOT NULL, -- 게시판 소유 크리에이터
    member_id BIGINT NOT NULL, -- 작성자 (유료 구독자 또는 소유 크리에이터)
    title VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'WAITING',
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_board_post_creator FOREIGN KEY (creator_id) REFERENCES member (id),
    CONSTRAINT fk_board_post_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT ck_board_post_type CHECK (
        type IN (
            'QUESTION',
            'FEEDBACK',
            'CONTENT_SUGGESTION',
            'MATERIAL',
            'GENERAL'
        )
    ),
    CONSTRAINT ck_board_post_status CHECK (status IN ('WAITING', 'ANSWERED'))
);

CREATE INDEX idx_board_post_creator ON board_post (creator_id, created_at DESC)
WHERE
    is_deleted = false;

CREATE INDEX idx_board_post_member ON board_post (member_id);

COMMENT ON TABLE board_post IS '유료 구독자 전용 Q&A 게시판 — 프로젝트와 무관. "공식 답변 등록 전까지만 수정 허용" 정책은 앱 레이어 책임(DECISION-006, 미확정)';

CREATE TABLE board_post_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_post_id BIGINT NOT NULL,
    url VARCHAR(500) NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    original_name VARCHAR(255),
    file_size BIGINT,
    mime_type VARCHAR(100),
    order_index INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_board_post_image_post FOREIGN KEY (board_post_id) REFERENCES board_post (id)
);

CREATE INDEX idx_board_post_image_post ON board_post_image (board_post_id, order_index);

COMMENT ON TABLE board_post_image IS '게시글 이미지 첨부 (BOARD-007, MEDIA-002)';

CREATE TABLE board_answer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_post_id BIGINT NOT NULL,
    creator_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uq_board_answer_post UNIQUE (board_post_id),
    CONSTRAINT fk_board_answer_post FOREIGN KEY (board_post_id) REFERENCES board_post (id),
    CONSTRAINT fk_board_answer_creator FOREIGN KEY (creator_id) REFERENCES member (id)
);

COMMENT ON TABLE board_answer IS '크리에이터 공식 답변 (BOARD-010~012) — 게시글당 1개';

CREATE TABLE board_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_post_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    parent_comment_id BIGINT,
    depth SMALLINT NOT NULL DEFAULT 0,
    content VARCHAR(1000) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_board_comment_post FOREIGN KEY (board_post_id) REFERENCES board_post (id),
    CONSTRAINT fk_board_comment_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_board_comment_parent FOREIGN KEY (parent_comment_id) REFERENCES board_comment (id),
    -- [NOTE] ERD에 board_comment 전용 "추가 제약조건" 표는 없으나 feed_comment와 동일 구조 → 동일 규칙 적용
    CONSTRAINT ck_board_comment_depth CHECK (depth IN (0, 1)),
    CONSTRAINT ck_board_comment_parent CHECK (
        (
            depth = 0
            AND parent_comment_id IS NULL
        )
        OR (
            depth = 1
            AND parent_comment_id IS NOT NULL
        )
    )
);

CREATE INDEX idx_board_comment_post ON board_comment (board_post_id, created_at);

/*
CREATE OR REPLACE FUNCTION fn_board_comment_check_parent() RETURNS TRIGGER AS $$
DECLARE
parent_post_id BIGINT;
BEGIN
IF NEW.parent_comment_id IS NOT NULL THEN
SELECT board_post_id INTO parent_post_id FROM board_comment WHERE id = NEW.parent_comment_id;
IF parent_post_id IS DISTINCT FROM NEW.board_post_id THEN
RAISE EXCEPTION 'board_comment.parent_comment_id(%) belongs to a different board_post', NEW.parent_comment_id;
END IF;
END IF;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_board_comment_check_parent
BEFORE INSERT OR UPDATE OF parent_comment_id, board_post_id ON board_comment
FOR EACH ROW EXECUTE FUNCTION fn_board_comment_check_parent();
*/
COMMENT ON TABLE board_comment IS '게시글 댓글·대댓글 (BOARD-013~014)';

-- ============================================================
-- 11. 1:1 채팅 (CHAT)
-- ============================================================
CREATE TABLE chat_room (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    closed_by BIGINT,
    closed_at TIMESTAMPTZ,
    last_message_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_chat_room_creator FOREIGN KEY (creator_id) REFERENCES member (id),
    CONSTRAINT fk_chat_room_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_chat_room_closer FOREIGN KEY (closed_by) REFERENCES member (id),
    CONSTRAINT uq_chat_room UNIQUE (creator_id, member_id),
    CONSTRAINT ck_chat_room_status CHECK (status IN ('ACTIVE', 'CLOSED'))
);

CREATE INDEX idx_chat_room_member ON chat_room (member_id, last_message_at DESC);

CREATE INDEX idx_chat_room_creator ON chat_room (creator_id, last_message_at DESC);

COMMENT ON TABLE chat_room IS '1:1 채팅방 (CHAT-001, 005, 008~012 / DECISION-008 기준 크리에이터·구독자 쌍당 1개). 생성은 활성 PAID 구독자만, 목록은 last_message_at 기준 최신순 — 둘 다 앱 레이어 책임';

CREATE TABLE chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    content VARCHAR(2000),
    image_url VARCHAR(500),
    image_storage_key VARCHAR(500),
    image_original_name VARCHAR(255),
    read_at TIMESTAMPTZ, -- 상대방이 읽은 시각, NULL = 안읽음
    sent_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_chat_message_room FOREIGN KEY (chat_room_id) REFERENCES chat_room (id),
    CONSTRAINT fk_chat_message_sender FOREIGN KEY (sender_id) REFERENCES member (id),
    CONSTRAINT ck_chat_message_type CHECK (type IN ('TEXT', 'IMAGE')),
    -- [NOTE] ERD엔 명시 없으나 빈 메시지 방지 위해 유형별 필수값 보완
    CONSTRAINT ck_chat_message_payload CHECK (
        (
            type = 'TEXT'
            AND content IS NOT NULL
        )
        OR (
            type = 'IMAGE'
            AND image_url IS NOT NULL
        )
    )
);

CREATE INDEX idx_chat_message_room ON chat_message (chat_room_id, sent_at DESC);

CREATE INDEX idx_chat_message_unread ON chat_message (chat_room_id, sender_id)
WHERE
    read_at IS NULL;

COMMENT ON TABLE chat_message IS '채팅 메시지 (CHAT-003~004, 006~007)';

-- ============================================================
-- 12. 알림 (NOTIFICATION)
-- ============================================================
CREATE TABLE notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL, -- 수신자
    sender_id BIGINT, -- 알림 원인 사용자, 시스템 알림은 NULL
    type VARCHAR(50) NOT NULL,
    message VARCHAR(500),
    reference_id BIGINT NOT NULL, -- 관련 엔티티 ID (다형 참조, FK 없음)
    reference_type VARCHAR(50) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_notification_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_notification_sender FOREIGN KEY (sender_id) REFERENCES member (id),
    CONSTRAINT ck_notification_type CHECK (
        type IN (
            -- 각 이벤트 형식 및 method에 대해서는 `slack - 개발 채널 - 기술-가이드 : 이벤트 기반 아키텍처 설계` 참고 (07/13, 02:44 - 미완 )
            'NEW_FEED', -- 새 피드 생성 이벤트 
            'FEED_COMMENT', -- 피드 댓글 생성 이벤트 
            'FEED_REPLY', -- 피드 대댓글 생성 이벤트
            'BOARD_ANSWER', --  
            'BOARD_COMMENT',
            'BOARD_REPLY',
            'CHAT_MESSAGE',
            'SUBSCRIPTION_EXPIRING',
            'PAYMENT_SUCCESS',
            'PAYMENT_FAILED',
            'POLL_VOTE',
            'CREATOR_APPLICATION_APPROVED',
            'CREATOR_APPLICATION_REJECTED'
        )
    )
);

CREATE INDEX idx_notification_member ON notification (member_id, created_at DESC);

CREATE INDEX idx_notification_unread ON notification (member_id)
WHERE
    is_read = false;

COMMENT ON TABLE notification IS '알림 — reference_id/reference_type 다형 참조(의도적 FK 미설정). 성민 메모: 트랜잭션 락 성능 검토';